DROP TABLE IF EXISTS messages;

CREATE TABLE messages(
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(25) NOT NULL,
  last_name VARCHAR(25) NOT NULL,
  email VARCHAR(50) NOT NULL,
  message VARCHAR(500) NOT NULL
);